### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by erewh0** [LewisFletcher/django-easy-docs#1]
Hi 
Am trying to install django-easy-docs and am getting an error when I try and run the server . 

Have  installed easy-docs in a copy of a project thats working ... and no issues with wsgi in the "source " project... 

File "C:\Users\midod\sandbox\cellar\v_cellar\Lib\site-packages\django\core\servers\basehttp.py", line 50, in get_internal_wsgi_application
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: WSGI application 'cellar.wsgi.application' could not be loaded; Error importing module.

**Comment by erewh0** [comment]
Correction ! error down to user error ! i.e. me ;) comma missing in the middleware section of settings.py

**Comment by LewisFletcher** [comment]
Classic! Feel free to open another issue if anything else comes up. Hope you enjoy the package!

**Comment by erewh0** [comment]
Thanks ... am trying to use it now so will ping you if anything comes up ,

 There are differences between the read the docs doc and pypi installation instructions , which would you recommend I follow , read-the-docs version ?

________________________________

**Comment by LewisFletcher** [comment]
Yes, the read the docs will be the most accurate.

**Comment by erewh0** [comment]
Thanks - I'll send a note with any comments / notes observations etc once done 🤞
________________________________

**Comment by erewh0** [comment]
Hi Lewis
Am getting the following error when using  the {% help_button %} tag
Happy to send more logs or details
--------------------------------------------------------------------------------

TypeError at /reports/add_wine

context must be a dict rather than RequestContext.

Request Method:
GET
Request URL:
http://127.0.0.1:8000/reports/add_wine
Django Version:
4.2.7
Exception Type:
TypeError
Exception Value:

context must be a dict rather than RequestContext.

Exception Location:
C:\Users\midod\sandbox\cellar\v_cellar\Lib\site-packages\django\template\context.py, line 278, in make_context
Raised during:
reports.views.add_wine




________________________________

**Comment by erewh0** [comment]
Also ... no migration files  were  created when I ran makemigrate ....


Mike
________________________________

**Comment by LewisFletcher** [comment]
Strange. Did you run migrate too? As for your exception, does removing the help button fix the error?

**Comment by erewh0** [comment]
*   yep tried running migrate -  nothing to migrate 🙁
  *   I've tried help button in a couple of modules with the same fail - the plan was to start writing docs for each page using the help button
     *   no fail if I take the help button {% help_button %} tag out ;  have left the   {% load easy_docs_tags %} in
     *   Start of template now looks like this :
        *
{%extends 'base.html' %}
{% load easy_docs_tags %}
{% block content %}
</div>
<h3> Full Cellar List </h3> <br>




  *   Final line in scripts ( below ) causes my navbar to lock out
     *    it's loaded with an include in base.html     ..... {% include 'partials/navbar.html' %}

  *




<script ***@***.***/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



________________________________

**Comment by LewisFletcher** [comment]
Did you add the {% load dependencies %} tag to your head? I think that's what is causing your issue. Sorry for the late response,

**Comment by erewh0** [comment]
Hi Lewis


Yes I had the load dependencies tag in my base.html  🙁
Mike
________________________________

**Comment by LewisFletcher** [comment]
Any other error context you can provide? I'm going to do some testing now
and see if I can replicate the error.

You definitely have the URL set up, and all the necessary apps added to
your installed apps, correct?

Lewis

**Comment by erewh0** [comment]
HiYes all of the other dependencies were met. The main thing that puzzles me is that There were no migrations …I did some digging and saw the documentation model in the easy docs app , but nothing was triggered in my project. I’m out for the next few days but can get you more logs etc Monday if that helps. Rgds,Mike DoddsOn 25 Jan 2024, at 17:28, Lewis Fletcher ***@***.***> wrote:﻿
Any other error context you can provide? I'm going to do some testing now

and see if I can replicate the error.



You definitely have the URL set up, and all the necessary apps added to

your installed apps, correct?



Lewis

**Comment by LewisFletcher** [comment]
No need. I was able to replicate both the issues you were having and have
pushed a new release. Install version 1.3.0 on Monday and you should be
good to go. You will only need to run "migrate" this time around.

Thanks for using my package!

**Comment by erewh0** [comment]
Great stuff, looking forward to trying the release ! Rgds,Mike DoddsOn 25 Jan 2024, at 21:41, Lewis Fletcher ***@***.***> wrote:﻿
No need. I was able to replicate both the issues you were having and have

pushed a new release. Install version 1.3.0 on Monday and you should be

good to go. You will only need to run "migrate" this time around.



Thanks for using my package!
